openapi: 3.0.3
info:
  title: AID Treatments Collection - De Facto 2025
  version: 2025.1.0
  description: |
    OpenAPI specification for the Nightscout `treatments` collection documenting
    the de facto standard as implemented across AID systems circa 2025.
    
    ## Data Flow
    - **Producers**: Loop, AAPS, Trio, xDrip+, Nightscout Careportal
    - **Consumers**: All AID systems, Nightscout web, follower apps, reporters
    
    ## Key Insights
    - `eventType` is the primary classification field
    - `syncIdentifier` vs `identifier` usage varies by controller (GAP-003)
    - SMB identification requires checking `type` field, not just `eventType`
    
    ## Source References
    - Deep Dive: `docs/10-domain/treatments-deep-dive.md`
    - Nightscout API: `externals/cgm-remote-monitor/lib/api3/swagger.yaml`

  contact:
    name: AID Alignment Workspace
  license:
    name: AGPL-3.0

servers:
  - url: /api/v3

paths:
  /treatments:
    get:
      summary: Search treatments
      operationId: searchTreatments
      tags: [treatments]
      parameters:
        - $ref: '#/components/parameters/createdAtFilter'
        - $ref: '#/components/parameters/eventTypeFilter'
        - $ref: '#/components/parameters/limit'
      responses:
        '200':
          description: Array of treatment documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Treatment'

components:
  parameters:
    createdAtFilter:
      name: created_at$gte
      in: query
      schema:
        type: string
        format: date-time
    eventTypeFilter:
      name: eventType
      in: query
      schema:
        $ref: '#/components/schemas/EventType'
    limit:
      name: limit
      in: query
      schema:
        type: integer
        default: 10
        maximum: 1000

  schemas:
    EventType:
      type: string
      description: |
        Treatment classification. This is the primary discriminator for treatment types.
        Note: The same `eventType` may have different semantics across controllers.
      enum:
        # Insulin events
        - Meal Bolus
        - Correction Bolus
        - Snack Bolus
        - Combo Bolus
        - Bolus Wizard
        # Carb events
        - Carb Correction
        # Basal events
        - Temp Basal
        - Temporary Target
        - Profile Switch
        - Temporary Override
        # Device events
        - Site Change
        - Sensor Start
        - Sensor Change
        - Insulin Change
        - Pump Battery Change
        - BG Check
        - Announcement
        - Note
        - Question
        - Exercise
        - OpenAPS Offline
        - Suspend Pump
        - Resume Pump
        # AAPS-specific
        - SMB
        - Target Range
        - NS Carbs
        # Legacy
        - Prime
        - <none>
      x-aid-source: docs/10-domain/treatments-deep-dive.md
      x-aid-controllers:
        Loop: Uses Meal Bolus, Correction Bolus, Temp Basal, Temporary Override
        AAPS: Full range including SMB, Profile Switch, Combo Bolus
        Trio: Similar to Loop, uses oref0 eventTypes
        xDrip: Primarily Carb Correction, BG Check, <none>

    BolusType:
      type: string
      enum: [Normal, Square, Dual]
      description: |
        Bolus delivery pattern:
        - Normal: Immediate delivery
        - Square: Extended over time
        - Dual: Immediate + extended

    Treatment:
      type: object
      required:
        - eventType
        - created_at
      properties:
        # Identity fields
        _id:
          type: string
          description: MongoDB document ID
        identifier:
          type: string
          description: |
            API v3 primary key. Server-assigned.
            AAPS uses this for sync identity.
          x-aid-controllers:
            AAPS: Primary sync field (interfaceIDs.nightscoutId)
            Loop: Not used (uses syncIdentifier)
            Trio: Not used (uses syncIdentifier)
        syncIdentifier:
          type: string
          description: |
            Client-assigned sync identity (UUID).
            Loop and Trio primary sync mechanism.
          x-aid-gap: GAP-003
          x-aid-gap-note: No unified sync identity field across controllers
          x-aid-controllers:
            Loop: Primary sync field (UUID string)
            Trio: Primary sync field (inherited from LoopKit)
            AAPS: Not used

        # Classification
        eventType:
          $ref: '#/components/schemas/EventType'
        
        # Timestamps
        created_at:
          type: string
          format: date-time
          description: Event timestamp (ISO 8601)
        timestamp:
          type: integer
          format: int64
          description: Epoch milliseconds (alternative to created_at)

        # Insulin fields
        insulin:
          type: number
          minimum: 0
          description: Insulin amount in Units
          x-aid-controllers:
            Loop: deliveredUnits (preferred) or programmedUnits
            AAPS: amount
            Trio: via DoseEntry
        programmed:
          type: number
          description: Originally programmed insulin (before cancellation)
        unabsorbed:
          type: number
          description: Unabsorbed insulin at time of bolus
        bolusType:
          $ref: '#/components/schemas/BolusType'
        automatic:
          type: boolean
          description: |
            Whether insulin was automatically delivered.
            true = auto-bolus/SMB, false = manual bolus
          x-aid-controllers:
            Loop: automatic field
            AAPS: Inferred from Bolus.Type (SMB = automatic)
            Trio: automatic field
        type:
          type: string
          description: |
            AAPS-specific bolus subtype.
            IMPORTANT: Check this field to identify SMBs, not just eventType.
          enum: [Normal, SMB, Priming]
          x-aid-controllers:
            AAPS: Bolus.Type.toBolusType()
            Loop: Not used
            Trio: Not used
          x-aid-gap: GAP-TREAT-002
          x-aid-gap-note: SMB identification requires type field check
        insulinType:
          type: string
          description: Insulin product name (Humalog, NovoRapid, Fiasp, etc.)
          x-aid-controllers:
            Loop: insulinType?.brandName
            AAPS: insulinConfiguration
            xDrip: insulinJSON (supports multiple)
          x-aid-gap: GAP-INS-001
          x-aid-gap-note: Insulin metadata not synced to Nightscout
        isBasalInsulin:
          type: boolean
          description: AAPS MDI basal injection tracking
          x-aid-controllers:
            AAPS: isBasalInsulin field
            Loop: Not applicable
            Trio: Not applicable

        # Carb fields
        carbs:
          type: number
          minimum: 0
          description: Carbohydrates in grams
          x-aid-controllers:
            Loop: quantity (HKQuantity grams)
            AAPS: amount
            Trio: via CarbsEntry
        absorptionTime:
          type: integer
          description: |
            Carb absorption time in MINUTES (Nightscout convention).
            WARNING: Loop/Trio use SECONDS internally.
          x-aid-gap: GAP-TREAT-001
          x-aid-gap-note: Unit mismatch - Loop/Trio use seconds, Nightscout uses minutes
          x-aid-controllers:
            Loop: absorptionTime / 60 (seconds to minutes)
            AAPS: Not stored (uses profile default)
            Trio: absorptionTime / 60 (seconds to minutes)
        foodType:
          type: string
          description: Food category/description
        fat:
          type: number
          description: Fat grams (for FPU calculation)
        protein:
          type: number
          description: Protein grams (for FPU calculation)

        # Basal fields
        duration:
          type: number
          description: |
            Duration in MINUTES for temp basal, override, eCarbs.
            WARNING: Loop enacted uses SECONDS.
          x-aid-gap: GAP-TREAT-003
          x-aid-gap-note: Duration unit inconsistency
          x-aid-controllers:
            Loop: Uses seconds in devicestatus.enacted
            AAPS: Uses minutes
            Trio: Uses seconds (LoopKit convention)
        percent:
          type: number
          description: Temp basal as percentage of scheduled basal
        absolute:
          type: number
          description: Temp basal as absolute rate (U/hr)
        rate:
          type: number
          description: Temp basal rate (U/hr) - alias for absolute
        temp:
          type: string
          enum: [absolute, percent]
          description: Whether temp basal is expressed as rate or percentage

        # Target/Override fields
        targetTop:
          type: number
          description: Upper target glucose (mg/dL)
        targetBottom:
          type: number
          description: Lower target glucose (mg/dL)
        reason:
          type: string
          description: Override/temp target reason (e.g., "Exercise", "Eating Soon")

        # Profile switch fields
        profile:
          type: string
          description: Profile name for profile switch
        percentage:
          type: integer
          description: AAPS profile percentage (100 = normal)
        timeshift:
          type: integer
          description: AAPS profile time shift in hours
        profileJson:
          type: string
          description: Full profile JSON (for inline profile switch)

        # BG Check fields
        glucose:
          type: number
          description: Blood glucose value at time of treatment
        glucoseType:
          type: string
          enum: [Sensor, Finger, Manual]
          description: Source of glucose reading

        # Metadata
        enteredBy:
          type: string
          description: |
            User/device nickname that created treatment.
            WARNING: Unverified free-form string.
          x-aid-gap: GAP-AUTH-001
          x-aid-gap-note: enteredBy is unverified, anyone can claim any identity
        notes:
          type: string
          description: Free-form notes
        device:
          type: string
          description: Device identifier
        app:
          type: string
          description: Application identifier

        # Pump identity (AAPS composite key)
        pumpId:
          type: integer
          format: int64
          description: Pump internal ID for this treatment
          x-aid-controllers:
            AAPS: interfaceIDs.pumpId
            Loop: Not used
        pumpType:
          type: string
          description: Pump type enum name
          x-aid-controllers:
            AAPS: interfaceIDs.pumpType
            Loop: Not used
        pumpSerial:
          type: string
          description: Pump serial number
          x-aid-controllers:
            AAPS: interfaceIDs.pumpSerial
            Loop: Not used

        # API v3 metadata
        utcOffset:
          type: integer
          description: Timezone offset in minutes
        srvCreated:
          type: integer
          format: int64
        srvModified:
          type: integer
          format: int64
        subject:
          type: string
        modifiedBy:
          type: string
        isValid:
          type: boolean
          default: true
        isReadOnly:
          type: boolean
          default: false

    # Override-specific schema (subset of Treatment)
    Override:
      allOf:
        - $ref: '#/components/schemas/Treatment'
        - type: object
          properties:
            eventType:
              const: Temporary Override
            reason:
              type: string
              description: Override preset name
            targetRange:
              type: object
              properties:
                minValue:
                  type: number
                maxValue:
                  type: number
            insulinNeedsScaleFactor:
              type: number
              description: |
                Overall insulin needs multiplier (1.0 = 100%).
                Loop-specific field.
              x-aid-controllers:
                Loop: overallInsulinNeedsScaleFactor
                AAPS: Uses profile percentage instead
                Trio: Uses oref1 profile percentage
            supersedes:
              type: string
              description: |
                2026 Extension: ID of override this supersedes.
                Addresses GAP-001 (override supersession tracking).
              x-aid-2026: true
              x-aid-gap: GAP-001

    # SMB-specific identification helper
    SMBIdentification:
      description: |
        How to reliably identify SMB treatments:
        1. Check `type === "SMB"` (AAPS)
        2. OR check `automatic === true` AND `insulin < threshold` (Loop/Trio auto-bolus)
        3. OR check `eventType === "Correction Bolus"` AND above conditions
        
        WARNING: Do NOT rely solely on eventType - AAPS uses "Correction Bolus" for SMBs
      x-aid-source: docs/10-domain/treatments-deep-dive.md#smb-representation
