"""sync_model.py — generate and check controller state-model registrations.

A registration (`specs/sync/controller-state-model.schema.json`) is what a
controller would tell a hub once, so the hub can prepare a sync contract for
it: the composite documents it writes, the primitives they decompose to, the
state machine it exposes, the dosing inputs it can supply, and the settings
it will publish.

The registrations here are **generated from the evidence already gathered**
rather than hand-written, so they cannot quietly claim more than was
measured:

* documents and paths from the census and `vendor-surface.json`
* decomposition targets from the measured Nocturne V4 routing
* replay inputs and their status from `dosing-input-sources.yaml`
* settings fields from the same, restricted to what is or could be published

The interesting output is the **replay-completeness** figure: the share of a
controller's declared dosing inputs that are actually recorded. It is low,
and it is the number `oref-digital-twin` is working around when it extracts
settings from screenshots.
"""

import argparse
import json
from pathlib import Path

import jsonschema
import yaml

from . import corpus

SCHEMA = "specs/sync/controller-state-model.schema.json"
OUT_DIR = "specs/sync/registrations"

# Which census/vendor evidence belongs to which controller, and how its
# documents are recognised in a shared collection.
CONTROLLERS = {
    "loop": {
        "vendor": "LoopKit", "product": "Loop", "family": "loop",
        "discriminator": ("loop", "is-object"),
        "surfaces": ["Loop/NightscoutKit", "Loop/NightscoutKit-dose"],
        "prefixes": ["loop."],
        "decomposes": ["ApsSnapshot", "PumpSnapshot", "UploaderSnapshot"],
        "spans": [("Override", ["active", "inactive"], True)],
    },
    "trio": {
        "vendor": "Nightscout Foundation", "product": "Trio", "family": "oref0",
        "discriminator": ("openaps", "is-object"),
        "surfaces": ["Trio", "Trio/determination", "Trio/iob"],
        "prefixes": ["openaps."],
        "decomposes": ["ApsSnapshot", "PumpSnapshot", "UploaderSnapshot"],
        "spans": [("Override", ["active", "inactive"], True),
                  ("TemporaryTarget", ["active", "inactive"], True)],
    },
    "androidaps": {
        "vendor": "AndroidAPS", "product": "AndroidAPS", "family": "oref0",
        "discriminator": ("openaps", "is-object"),
        "surfaces": ["AndroidAPS"],
        "prefixes": ["openaps."],
        "decomposes": ["ApsSnapshot", "PumpSnapshot", "UploaderSnapshot"],
        "spans": [("Override", ["active", "inactive"], True),
                  ("TemporaryTarget", ["active", "inactive"], True),
                  ("ProfileState", ["active"], True)],
    },
}

CYCLE_SECONDS = 300


def _load(root, rel):
    path = root / rel
    return json.loads(path.read_text()) if path.is_file() else None


def build(root: Path, key: str, spec: dict):
    census = _load(root, "reports/schema-census/devicestatus.census.json") or {"fields": []}
    vendor = _load(root, "reports/schema-census/vendor-surface.json") or {"surfaces": {}}
    dosing = yaml.safe_load(
        (root / "specs/nsschema/dosing-input-sources.yaml").read_text())

    observed = {f["path"] for f in census["fields"]}
    paths = sorted(p for p in observed
                   if any(p.startswith(pre) for pre in spec["prefixes"]))

    declared = set()
    for label in spec["surfaces"]:
        declared.update(vendor["surfaces"].get(label, {}).get("names", []))

    replay = []
    for entry in dosing["inputs"]:
        if entry.get("algorithm") != spec["family"]:
            continue
        sources = entry.get("sources") or []
        replay.append({
            "input": entry["input"],
            "path": sources[0] if sources else None,
            "collection": entry.get("collection") if sources else None,
            "status": entry["kind"],
        })

    settings_fields = sorted(
        e["input"] for e in dosing["inputs"]
        if e.get("algorithm") == spec["family"]
        and e["kind"] in ("absent", "partial")
        and e["input"].startswith(("profile.", "automatic", "carb", "recommendation",
                                   "use", "include", "max", "gradual")))

    return {
        "apiVersion": "nightscout.dev/sync/v1",
        "kind": "ControllerStateModel",
        "metadata": {
            "vendor": spec["vendor"],
            "product": spec["product"],
            "algorithmFamily": spec["family"],
            "source": "generated by tools/nsschema/sync_model.py from the census, "
                      "vendor-surface.json and dosing-input-sources.yaml",
        },
        "spec": {
            "cadence": {"nominalSeconds": CYCLE_SECONDS,
                        "maxDeferralSeconds": CYCLE_SECONDS * 3},
            "documents": [
                {
                    "collection": "devicestatus",
                    "discriminator": {"path": spec["discriminator"][0],
                                      "test": spec["discriminator"][1]},
                    "decomposesTo": spec["decomposes"],
                    "paths": paths,
                },
                {"collection": "entries", "decomposesTo": ["SensorGlucose"]},
                {"collection": "treatments",
                 "decomposesTo": ["Bolus", "CarbIntake", "TempBasal", "BGCheck",
                                  "DeviceEvent", "Note"]},
                {"collection": "profile",
                 "decomposesTo": ["TherapySettings", "BasalSchedule",
                                  "CarbRatioSchedule", "SensitivitySchedule",
                                  "TargetRangeSchedule"]},
            ],
            "stateSpans": [
                {"category": c, "states": s, "supersedes": sup}
                for c, s, sup in spec["spans"]
            ],
            "replayInputs": sorted(replay, key=lambda r: r["input"]),
            "settings": {
                "resource": "ControllerSettings",
                "effectiveDated": True,
                "fields": settings_fields,
            },
            "sensitivity": {
                "labelsSource": "specs/jsonschema/generated/"
                                " (x-sensitivity, x-data-category)",
                "enforcesLocally": False,
                "supportedProfiles": ["full", "clinical", "replay", "effect-only"],
                "defaultProfile": "clinical",
                "unlabelledPolicy": "withhold",
            },
            "queryProfile": {
                "filterableFields": ["date", "created_at", "srvModified", "identifier"],
                "maxPageSize": 1000,
                "operators": ["eq", "gt", "gte", "lt", "lte", "in"],
            },
        },
        "x-declared-but-unobserved": sorted(
            n for n in declared
            if not any(p.split(".")[-1] == n for p in observed)),
    }


def completeness(registration):
    inputs = registration["spec"]["replayInputs"]
    if not inputs:
        return {}
    counts = {}
    for row in inputs:
        counts[row["status"]] = counts.get(row["status"], 0) + 1
    recorded = counts.get("recorded", 0)
    return {
        "inputs": len(inputs),
        "by_status": counts,
        "recorded_share": round(recorded / len(inputs), 4),
        "replayable_share": round(
            (recorded + counts.get("derivable", 0)) / len(inputs), 4),
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default=OUT_DIR, type=Path)
    ap.add_argument("--check", action="store_true",
                    help="validate committed registrations and exit non-zero on drift")
    args = ap.parse_args(argv)

    root = corpus.repo_root()
    schema = json.loads((root / SCHEMA).read_text())
    validator = jsonschema.Draft202012Validator(schema)
    out_dir = root / args.out
    out_dir.mkdir(parents=True, exist_ok=True)

    stale = []
    for key, spec in CONTROLLERS.items():
        registration = build(root, key, spec)
        # x- fields are informational; the schema does not allow them.
        checked = {k: v for k, v in registration.items() if not k.startswith("x-")}
        errors = sorted(validator.iter_errors(checked), key=lambda e: e.path)
        if errors:
            for error in errors[:3]:
                print(f"  {key}: INVALID {list(error.path)}: {error.message}")
            return 1

        dest = out_dir / f"{key}.yaml"
        text = yaml.safe_dump(registration, sort_keys=False, width=88)
        if args.check:
            if not dest.is_file() or dest.read_text() != text:
                stale.append(dest.relative_to(root))
        else:
            dest.write_text(text)

        stats = completeness(registration)
        print(f"  {key:11s} {len(registration['spec']['documents'])} documents, "
              f"{len(registration['spec']['replayInputs'])} replay inputs, "
              f"recorded {stats['recorded_share']:.0%}, "
              f"replayable {stats['replayable_share']:.0%}, "
              f"settings to publish: {len(registration['spec']['settings']['fields'])}")

    if args.check and stale:
        for path in stale:
            print(f"STALE {path}")
        print("\nRun: make schema-sync-model", file=__import__("sys").stderr)
        return 1
    if not args.check:
        print(f"-> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
