#!/usr/bin/env python3
"""
Reference generator for the alignment workspace.

Reads workspace.lock.json and generates:
1. docs/_generated/permalinks.json - mapping of code refs to GitHub URLs
2. docs/_generated/refs-summary.md - human-readable reference summary

Usage:
    python tools/gen_refs.py              # Generate all
    python tools/gen_refs.py --json-only  # Only generate JSON
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).parent.parent
LOCKFILE = WORKSPACE_ROOT / "workspace.lock.json"
GENERATED_DIR = WORKSPACE_ROOT / "docs" / "_generated"


def load_lockfile():
    """Load and parse workspace.lock.json."""
    if not LOCKFILE.exists():
        print(f"Error: {LOCKFILE} not found")
        sys.exit(1)
    with open(LOCKFILE) as f:
        return json.load(f)


def generate_github_url(repo, path, anchor=None):
    """Generate a GitHub permalink for a file."""
    base_url = repo["url"].replace(".git", "")
    ref = repo.get("sha") or repo.get("ref", "main")
    
    url = f"{base_url}/blob/{ref}/{path}"
    
    if anchor:
        # Convert L10-L50 to GitHub format #L10-L50
        url += f"#{anchor}"
    
    return url


def generate_permalinks(lockfile_data):
    """Generate permalinks.json mapping."""
    permalinks = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "repos": {},
        "refs": {}
    }
    
    for repo in lockfile_data.get("repos", []):
        alias = repo.get("alias", repo["name"])
        base_url = repo["url"].replace(".git", "")
        ref = repo.get("sha") or repo.get("ref", "main")
        
        permalinks["repos"][alias] = {
            "name": repo["name"],
            "url": base_url,
            "ref": ref,
            "sha": repo.get("sha"),
            "local_path": f"{lockfile_data.get('externals_dir', 'externals')}/{repo['name']}"
        }
    
    return permalinks


def generate_summary(lockfile_data):
    """Generate refs-summary.md content."""
    lines = [
        "# Code Reference Summary",
        "",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "",
        "This file is auto-generated by `tools/gen_refs.py`. Do not edit manually.",
        "",
        "## Repositories",
        "",
        "| Alias | Name | Branch/SHA | Status |",
        "|-------|------|------------|--------|",
    ]
    
    for repo in lockfile_data.get("repos", []):
        alias = repo.get("alias", repo["name"])
        name = repo["name"]
        ref = repo.get("ref", "main")
        sha = repo.get("sha")
        
        if sha:
            ref_display = f"`{sha[:7]}` ({ref})"
            status = "Pinned"
        else:
            ref_display = f"`{ref}`"
            status = "Floating"
        
        lines.append(f"| `{alias}` | {name} | {ref_display} | {status} |")
    
    lines.extend([
        "",
        "## Usage",
        "",
        "Reference format: `alias:path/to/file.ext#anchor`",
        "",
        "Examples:",
        "- `crm:lib/server/treatments.js` - file reference",
        "- `loop:Loop/Models/Override.swift#L10-L50` - with line range",
        "",
        "## Quick Links",
        "",
    ])
    
    for repo in lockfile_data.get("repos", []):
        alias = repo.get("alias", repo["name"])
        name = repo["name"]
        base_url = repo["url"].replace(".git", "")
        ref = repo.get("sha") or repo.get("ref", "main")
        
        lines.append(f"- [{name}]({base_url}/tree/{ref})")
    
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate code reference files")
    parser.add_argument("--json-only", action="store_true", help="Only generate JSON file")
    args = parser.parse_args()
    
    lockfile_data = load_lockfile()
    
    # Ensure output directory exists
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    
    # Generate permalinks.json
    permalinks = generate_permalinks(lockfile_data)
    permalinks_path = GENERATED_DIR / "permalinks.json"
    with open(permalinks_path, "w") as f:
        json.dump(permalinks, f, indent=2)
    print(f"Generated: {permalinks_path}")
    
    # Generate summary markdown
    if not args.json_only:
        summary = generate_summary(lockfile_data)
        summary_path = GENERATED_DIR / "refs-summary.md"
        with open(summary_path, "w") as f:
            f.write(summary)
        print(f"Generated: {summary_path}")
    
    print("\nDone!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
